name: skillbridge
description: "A comprehensive Flutter application that bridges the gap between skills and opportunities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  # Authentication
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Add custom fonts if needed
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: fonts/SFProDisplay-Regular.ttf
  #       - asset: fonts/SFProDisplay-Bold.ttf
  #         weight: 700