// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96HBP9-oS2Ce707Ku89pLL0zmA1fMMYE',
    appId: '1:708432497622:web:ce67f6d3574d15052f3277',
    messagingSenderId: '708432497622',
    projectId: 'skillbridge-979ed',
    authDomain: 'skillbridge-979ed.firebaseapp.com',
    storageBucket: 'skillbridge-979ed.firebasestorage.app',
    measurementId: 'G-LDQH0K2N10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIv5-960mtMhhueoSoQClc5wKjA1syJIM',
    appId: '1:708432497622:android:22bfd17772e6ccce2f3277',
    messagingSenderId: '708432497622',
    projectId: 'skillbridge-979ed',
    storageBucket: 'skillbridge-979ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJPJJtuNe74L2EUHZ_hg8cW8I9fARtqE',
    appId: '1:708432497622:ios:61d121e85d0c13182f3277',
    messagingSenderId: '708432497622',
    projectId: 'skillbridge-979ed',
    storageBucket: 'skillbridge-979ed.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoJPJJtuNe74L2EUHZ_hg8cW8I9fARtqE',
    appId: '1:708432497622:ios:61d121e85d0c13182f3277',
    messagingSenderId: '708432497622',
    projectId: 'skillbridge-979ed',
    storageBucket: 'skillbridge-979ed.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC96HBP9-oS2Ce707Ku89pLL0zmA1fMMYE',
    appId: '1:708432497622:web:5e833899277fc3612f3277',
    messagingSenderId: '708432497622',
    projectId: 'skillbridge-979ed',
    authDomain: 'skillbridge-979ed.firebaseapp.com',
    storageBucket: 'skillbridge-979ed.firebasestorage.app',
    measurementId: 'G-2CTC9YGG8Y',
  );
}
